-- ============================================================
--  Control de asistencia - Mercados Don Manuel
--  Script de creacion de tablas y bucket de fotos en Supabase.
--
--  COMO USARLO: en tu proyecto de Supabase, menu "SQL Editor" ->
--  "New query" -> pega TODO este archivo -> boton "Run".
--  Se puede ejecutar varias veces sin problema.
-- ============================================================

create table if not exists empleados (
    id         bigint generated by default as identity primary key,
    nombre     text not null unique,
    cargo      text default '',
    pin        text default '',
    activo     boolean not null default true,
    creado_en  timestamp not null default now()
);

create table if not exists horarios (
    id            bigint generated by default as identity primary key,
    empleado_id   bigint not null references empleados(id) on delete cascade,
    dia_semana    integer not null check (dia_semana between 0 and 6),
    hora_entrada  time not null,
    hora_salida   time not null,
    jornada_min   integer,
    unique (empleado_id, dia_semana)
);

-- (actualizaciones) turno partido: segundo bloque y jornada
alter table horarios add column if not exists jornada_min integer;
alter table horarios add column if not exists hora_entrada2 time;
alter table horarios add column if not exists hora_salida2 time;

-- Turnos programados por fecha (cuando una semana difiere del horario base)
create table if not exists turnos (
    id             bigint generated by default as identity primary key,
    empleado_id    bigint not null references empleados(id) on delete cascade,
    fecha          date not null,
    libre          boolean not null default false,
    hora_entrada   time,
    hora_salida    time,
    hora_entrada2  time,
    hora_salida2   time,
    nota           text default '',
    unique (empleado_id, fecha)
);
alter table turnos enable row level security;

-- Sedes (tiendas) y sede por dia
create table if not exists sedes (
    id      bigint generated by default as identity primary key,
    nombre  text not null unique,
    activa  boolean not null default true
);
alter table sedes enable row level security;
insert into sedes (nombre) values ('Gourmet'), ('Parque') on conflict (nombre) do nothing;
alter table empleados add column if not exists sede text default '';
alter table horarios  add column if not exists sede text default '';
alter table turnos    add column if not exists sede text default '';

create table if not exists registros (
    id           bigint generated by default as identity primary key,
    empleado_id  bigint not null references empleados(id) on delete cascade,
    tipo         text not null check (tipo in ('entrada', 'salida')),
    fecha        date not null,
    fecha_hora   timestamp not null,
    foto         text default '',
    nota         text default '',
    creado_en    timestamp not null default now()
);

create index if not exists idx_registros_emp_fecha on registros (empleado_id, fecha);
alter table registros add column if not exists sede text default '';

create table if not exists config (
    clave  text primary key,
    valor  text not null
);

-- Contrasena inicial del administrador: admin  (cambiala desde la app)
insert into config (clave, valor) values
    ('admin_password', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918'),
    ('tolerancia_min', '10'),
    ('contar_entrada_anticipada', '0')
on conflict (clave) do nothing;

-- Seguridad: la app usa la clave "service_role" (solo en el servidor), que
-- salta estas reglas. Con RLS activo y sin politicas, nadie mas puede leer
-- las tablas con la clave publica "anon".
alter table empleados enable row level security;
alter table horarios  enable row level security;
alter table registros enable row level security;
alter table config    enable row level security;

-- Bucket privado para las fotos
insert into storage.buckets (id, name, public)
values ('fotos', 'fotos', false)
on conflict (id) do nothing;
